package com.bean.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BABY".
 */
public class Baby implements java.io.Serializable {

    private Long id;
    private String bid;
    private String fid;
    private String name;
    private String age;
    private String sex;
    private String weight;
    private String hight;
    private String deviceName;
    private String img;
    private Boolean isconnect;

    public Baby() {
    }

    public Baby(Long id) {
        this.id = id;
    }

    public Baby(Long id, String bid, String fid, String name, String age, String sex, String weight, String hight, String deviceName, String img, Boolean isconnect) {
        this.id = id;
        this.bid = bid;
        this.fid = fid;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.weight = weight;
        this.hight = hight;
        this.deviceName = deviceName;
        this.img = img;
        this.isconnect = isconnect;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBid() {
        return bid;
    }

    public void setBid(String bid) {
        this.bid = bid;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getHight() {
        return hight;
    }

    public void setHight(String hight) {
        this.hight = hight;
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public Boolean getIsconnect() {
        return isconnect;
    }

    public void setIsconnect(Boolean isconnect) {
        this.isconnect = isconnect;
    }

}
