package com.bean.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHART".
 */
public class Chart {

    private Long id;
    private String cid;
    private String uid;
    private String bid;
    private String temperature;
    private String time;
    private String date;

    public Chart() {
    }

    public Chart(Long id) {
        this.id = id;
    }

    public Chart(Long id, String cid, String uid, String bid, String temperature, String time, String date) {
        this.id = id;
        this.cid = cid;
        this.uid = uid;
        this.bid = bid;
        this.temperature = temperature;
        this.time = time;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getBid() {
        return bid;
    }

    public void setBid(String bid) {
        this.bid = bid;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
