package com.bean.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_RECENT".
 */
public class SearchRecent {

    private Long id;
    private String title;
    private String other;

    public SearchRecent() {
    }

    public SearchRecent(Long id) {
        this.id = id;
    }

    public SearchRecent(Long id, String title, String other) {
        this.id = id;
        this.title = title;
        this.other = other;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

}
