package com.bean.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TREAT".
 */
public class Treat {

    private Long id;
    private String tid;
    private String uid;
    private String bid;
    private String temperature;
    private String time;
    private String date;
    private String physics;
    private String medicine;

    public Treat() {
    }

    public Treat(Long id) {
        this.id = id;
    }

    public Treat(Long id, String tid, String uid, String bid, String temperature, String time, String date, String physics, String medicine) {
        this.id = id;
        this.tid = tid;
        this.uid = uid;
        this.bid = bid;
        this.temperature = temperature;
        this.time = time;
        this.date = date;
        this.physics = physics;
        this.medicine = medicine;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getBid() {
        return bid;
    }

    public void setBid(String bid) {
        this.bid = bid;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getPhysics() {
        return physics;
    }

    public void setPhysics(String physics) {
        this.physics = physics;
    }

    public String getMedicine() {
        return medicine;
    }

    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }

}
