package com.bean.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bean.entity.User;
import com.bean.entity.Baby;

import com.bean.dao.UserDao;
import com.bean.dao.BabyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig babyDaoConfig;

    private final UserDao userDao;
    private final BabyDao babyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        babyDaoConfig = daoConfigMap.get(BabyDao.class).clone();
        babyDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        babyDao = new BabyDao(babyDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Baby.class, babyDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        babyDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BabyDao getBabyDao() {
        return babyDao;
    }

}
