package com.bean.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bean.entity.User;
import com.bean.entity.Baby;
import com.bean.entity.Chart;
import com.bean.entity.Treat;

import com.bean.dao.UserDao;
import com.bean.dao.BabyDao;
import com.bean.dao.ChartDao;
import com.bean.dao.TreatDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig babyDaoConfig;
    private final DaoConfig chartDaoConfig;
    private final DaoConfig treatDaoConfig;

    private final UserDao userDao;
    private final BabyDao babyDao;
    private final ChartDao chartDao;
    private final TreatDao treatDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        babyDaoConfig = daoConfigMap.get(BabyDao.class).clone();
        babyDaoConfig.initIdentityScope(type);

        chartDaoConfig = daoConfigMap.get(ChartDao.class).clone();
        chartDaoConfig.initIdentityScope(type);

        treatDaoConfig = daoConfigMap.get(TreatDao.class).clone();
        treatDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        babyDao = new BabyDao(babyDaoConfig, this);
        chartDao = new ChartDao(chartDaoConfig, this);
        treatDao = new TreatDao(treatDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Baby.class, babyDao);
        registerDao(Chart.class, chartDao);
        registerDao(Treat.class, treatDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        babyDaoConfig.getIdentityScope().clear();
        chartDaoConfig.getIdentityScope().clear();
        treatDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BabyDao getBabyDao() {
        return babyDao;
    }

    public ChartDao getChartDao() {
        return chartDao;
    }

    public TreatDao getTreatDao() {
        return treatDao;
    }

}
